# Pipeline for building the container image that is used by other pipelines for scoring.

resources:
  containers:
  - container: mlops
    image: mcr.microsoft.com/mlops/python:latest

pr: none
trigger:
  branches:
    include:
    - master
  paths:
    include:
    - ml_service/util/Dockerfile
    - diabetes_regression/scoring/
    exclude:
    - diabetes_regression/scoring/deployment_config_aci.yml
    - diabetes_regression/scoring/deployment_config_aks.yml

pool: 
  vmImage: 'ubuntu-latest'

container: mlops

variables:
- group: devopsforai-aml-vg

steps:
- template: diabetes_regression-package-model-template.yml
  parameters:
    modelId: $(MODEL_NAME):$(MODEL_VERSION)
    workingDirectory: '$(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/scoring'
    inferencePath: 'inference_config.yml'

